### ISSUE TITLE
I am lack the code of “latexTable-master”

### ISSUE THREAD

**Issue by lyf-123** [Aarian/Watermark_Detector#1]
I am lack the code of “latexTable-master”，can you give me？

**Comment by Aarian** [comment]
Hi, 
“latexTable-master” is just a tool for table making in latex format. It's not related to code. I just used it to write my report. 
for more information please see [here](https://www.mathworks.com/matlabcentral/fileexchange/44274-latextable)
you can simply comment `addpath('D:\MSC\Term2\Random process\HWs\HW3\Code\latexTable-master')` and run it.
